import os
import json
import uuid
from datetime import datetime, timezone
 
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
from groq import Groq

from stylometrics import get_stylometric_signal, compute_confidence, get_label
 
load_dotenv()
 
app = Flask(__name__)

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
 
LOG_FILE = "audit_log.json"
 
 
# ---------- Audit log helpers ----------
 
def get_log():
    """Read all entries from the audit log file. Returns an empty list if the file doesn't exist yet."""
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)
 
 
def write_log_entry(entry):
    """Append a single entry to the audit log file."""
    entries = get_log()
    entries.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def write_log(entries):
    """Overwrite the audit log file with the given list of entries."""
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)
 
 
# ---------- Detection signal 1: Groq LLM ----------
 
def get_llm_signal(text):
    """
    Sends the text to Groq and asks it to assess how likely the text is to be
    AI-generated. Returns a float between 0 and 1, where higher values mean
    higher likelihood of AI authorship.
 
    Returns None if the API call fails, so calling code can handle the error.
    """
    prompt = f"""You are a text-provenance classifier. Read the following text and
estimate the probability that it was generated by an AI language model
(as opposed to written by a human).
 
Respond with ONLY a single number between 0 and 1 (e.g. "0.73").
Do not include any other words, explanation, or punctuation.
 
TEXT:
\"\"\"{text}\"\"\"
"""
 
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=10,
        )
        raw_output = response.choices[0].message.content.strip()
        score = float(raw_output)
        # Clamp to [0, 1] in case the model returns something slightly out of range
        return max(0.0, min(1.0, score))
    except Exception as e:
        print(f"[get_llm_signal] Error calling Groq API: {e}")
        return None
 
 
# ---------- Label text ----------

def generate_label_text(label):
    """Maps a label key to the exact user-facing transparency label text."""
    label_texts = {
        "likely_ai": (
            "This content shows strong signals of AI generation. Our system detected "
            "patterns commonly associated with AI-written text across multiple "
            "independent checks."
        ),
        "uncertain": (
            "We can't confidently determine whether this content is AI-generated or "
            "human-written. Our detection signals produced mixed or inconclusive results."
        ),
        "likely_human": (
            "This content shows strong signals of human authorship. Our system found "
            "patterns consistent with human writing across multiple independent checks."
        ),
    }
    return label_texts.get(label, "")


# ---------- Routes ----------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(force=True, silent=True) or {}
    text = data.get("text")
    creator_id = data.get("creator_id")
 
    if not text or not creator_id:
        return jsonify({"error": "Both 'text' and 'creator_id' are required."}), 400
 
    content_id = str(uuid.uuid4())
 
    llm_score = get_llm_signal(text)

    if llm_score is None:
        return jsonify({"error": "Detection signal failed. Please try again."}), 502

    style_score = get_stylometric_signal(text)
    confidence = compute_confidence(llm_score, style_score)
    label = get_label(confidence)
    label_text = generate_label_text(label)

    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "llm_score": llm_score,
        "style_score": style_score,
        "confidence": confidence,
        "attribution": label,
        "status": "classified",
    }
    write_log_entry(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": label,
        "confidence": confidence,
        "label": label,
        "label_text": label_text,
    })
 
 
@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(force=True, silent=True) or {}
    content_id = data.get("content_id")
    creator_reasoning = data.get("creator_reasoning")

    if not content_id or not creator_reasoning:
        return jsonify(
            {"error": "Both 'content_id' and 'creator_reasoning' are required."}
        ), 400

    entries = get_log()
    matched = [e for e in entries if e.get("content_id") == content_id]
    if not matched:
        return jsonify({"error": f"No content found with content_id '{content_id}'."}), 404

    # Update the original classification entry's status to "under_review"
    for e in entries:
        if e.get("content_id") == content_id and e.get("status") == "classified":
            e["status"] = "under_review"
    write_log(entries)

    # Append a new log entry recording the appeal
    appeal_entry = {
        "content_id": content_id,
        "creator_reasoning": creator_reasoning,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "status": "under_review",
    }
    write_log_entry(appeal_entry)

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been received and the content is now under review.",
    })


@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})
 
 
if __name__ == "__main__":
    app.run(debug=True)