import os
import json
import uuid
from datetime import datetime, timezone
 
from flask import Flask, request, jsonify
from dotenv import load_dotenv
from groq import Groq
 
load_dotenv()
 
app = Flask(__name__)
 
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
 
LOG_FILE = "audit_log.json"
 
 
# ---------- Audit log helpers ----------
 
def get_log():
    """Read all entries from the audit log file. Returns an empty list if the file doesn't exist yet."""
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)
 
 
def write_log_entry(entry):
    """Append a single entry to the audit log file."""
    entries = get_log()
    entries.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)
 
 
# ---------- Detection signal 1: Groq LLM ----------
 
def get_llm_signal(text):
    """
    Sends the text to Groq and asks it to assess how likely the text is to be
    AI-generated. Returns a float between 0 and 1, where higher values mean
    higher likelihood of AI authorship.
 
    Returns None if the API call fails, so calling code can handle the error.
    """
    prompt = f"""You are a text-provenance classifier. Read the following text and
estimate the probability that it was generated by an AI language model
(as opposed to written by a human).
 
Respond with ONLY a single number between 0 and 1 (e.g. "0.73").
Do not include any other words, explanation, or punctuation.
 
TEXT:
\"\"\"{text}\"\"\"
"""
 
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=10,
        )
        raw_output = response.choices[0].message.content.strip()
        score = float(raw_output)
        # Clamp to [0, 1] in case the model returns something slightly out of range
        return max(0.0, min(1.0, score))
    except Exception as e:
        print(f"[get_llm_signal] Error calling Groq API: {e}")
        return None
 
 
# ---------- Routes ----------
 
@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json(force=True, silent=True) or {}
    text = data.get("text")
    creator_id = data.get("creator_id")
 
    if not text or not creator_id:
        return jsonify({"error": "Both 'text' and 'creator_id' are required."}), 400
 
    content_id = str(uuid.uuid4())
 
    llm_score = get_llm_signal(text)
 
    if llm_score is None:
        return jsonify({"error": "Detection signal failed. Please try again."}), 502
 
    # Placeholder confidence/label until Milestone 4 adds the second signal + real scoring
    confidence = llm_score
    label = "placeholder - real scoring comes in Milestone 4"
 
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "llm_score": llm_score,
        "confidence": confidence,
        "attribution": label,
        "status": "classified",
    }
    write_log_entry(log_entry)
 
    return jsonify({
        "content_id": content_id,
        "attribution": label,
        "confidence": confidence,
        "label": label,
    })
 
 
@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})
 
 
if __name__ == "__main__":
    app.run(debug=True)